
export interface Prescription {
  disease: string;
  medicines: Array<{
    name: string;
    dosage: string;
    notes?: string;
  }>;
  symptoms: string[];
  date: string;
  doctorName: string;
}

export function generatePDF(prescription: Prescription) {
  // Create a simple HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Medical Prescription</title>
      <style>
        body { 
          font-family: Arial, sans-serif; 
          margin: 20px; 
          line-height: 1.6;
          color: #333;
        }
        .header { 
          text-align: center; 
          border-bottom: 3px solid #4F46E5; 
          padding-bottom: 20px; 
          margin-bottom: 30px;
        }
        .title { 
          color: #4F46E5; 
          font-size: 28px; 
          font-weight: bold; 
          margin: 0;
        }
        .subtitle { 
          color: #6B7280; 
          font-size: 14px; 
          margin: 5px 0 0 0;
        }
        .info-section { 
          margin-bottom: 25px; 
          padding: 15px;
          background-color: #F9FAFB;
          border-radius: 8px;
          border-left: 4px solid #10B981;
        }
        .section-title { 
          color: #374151; 
          font-size: 16px; 
          font-weight: bold; 
          margin-bottom: 10px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .medicine-item { 
          margin-bottom: 15px; 
          padding: 12px;
          background-color: white;
          border-radius: 6px;
          border: 1px solid #E5E7EB;
        }
        .medicine-name { 
          font-weight: bold; 
          color: #1F2937; 
          font-size: 14px;
        }
        .medicine-dosage { 
          color: #6B7280; 
          font-size: 13px; 
          margin-top: 3px;
        }
        .medicine-notes { 
          color: #059669; 
          font-size: 12px; 
          font-style: italic; 
          margin-top: 3px;
        }
        .symptoms { 
          display: flex; 
          flex-wrap: wrap; 
          gap: 8px; 
        }
        .symptom-tag { 
          background-color: #DBEAFE; 
          color: #1E40AF; 
          padding: 4px 12px; 
          border-radius: 20px; 
          font-size: 12px;
          border: 1px solid #BFDBFE;
        }
        .footer { 
          margin-top: 40px; 
          padding-top: 20px; 
          border-top: 2px solid #E5E7EB; 
          font-size: 12px; 
          color: #6B7280;
        }
        .warning-box {
          background-color: #FEF3C7;
          border: 1px solid #F59E0B;
          border-radius: 6px;
          padding: 15px;
          margin-top: 20px;
        }
        .warning-title {
          color: #92400E;
          font-weight: bold;
          margin-bottom: 8px;
        }
        .warning-text {
          color: #92400E;
          font-size: 12px;
          line-height: 1.4;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">🏥 MEDICAL PRESCRIPTION</h1>
        <p class="subtitle">Generated by MedVoice AI Assistant</p>
      </div>
      
      <div class="info-section">
        <div style="display: flex; justify-content: space-between; align-items: start;">
          <div>
            <strong>Doctor:</strong> ${prescription.doctorName}<br>
            <span style="color: #6B7280; font-size: 13px;">AI Healthcare Assistant</span>
          </div>
          <div style="text-align: right;">
            <strong>Date:</strong> ${prescription.date}
          </div>
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">🔍 Diagnosis</div>
        <div style="font-size: 18px; font-weight: bold; color: #1F2937;">${prescription.disease}</div>
      </div>

      <div class="info-section">
        <div class="section-title">🩺 Symptoms</div>
        <div class="symptoms">
          ${prescription.symptoms.map(symptom => `<span class="symptom-tag">${symptom}</span>`).join('')}
        </div>
      </div>

      <div class="info-section">
        <div class="section-title">💊 Prescribed Medicines</div>
        ${prescription.medicines.map((medicine, index) => `
          <div class="medicine-item">
            <div style="display: flex; align-items: start;">
              <div style="background-color: #10B981; color: white; width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: bold; margin-right: 12px; flex-shrink: 0;">
                ${index + 1}
              </div>
              <div style="flex: 1;">
                <div class="medicine-name">${medicine.name}</div>
                <div class="medicine-dosage">Dosage: ${medicine.dosage}</div>
                ${medicine.notes ? `<div class="medicine-notes">Note: ${medicine.notes}</div>` : ''}
              </div>
            </div>
          </div>
        `).join('')}
      </div>

      <div class="warning-box">
        <div class="warning-title">⚠️ Important Instructions</div>
        <div class="warning-text">
          • Take medicines exactly as prescribed<br>
          • Complete the full course of treatment<br>
          • Consult your doctor if symptoms persist or worsen<br>
          • Store medicines in a cool, dry place away from children<br>
          • Do not share medicines with others<br>
          • Read medicine labels carefully before use
        </div>
      </div>

      <div class="footer">
        <div style="text-align: center;">
          <p><strong>For medical emergencies, contact your local emergency services immediately</strong></p>
          <p>This prescription was generated by MedVoice AI Assistant. For serious medical conditions, please consult with a licensed healthcare professional.</p>
          <p style="margin-top: 15px; font-size: 11px; color: #9CA3AF;">Generated on ${new Date().toLocaleString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;

  // Create a blob with the HTML content
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  // Create a temporary link and trigger download
  const link = document.createElement('a');
  link.href = url;
  link.download = `prescription_${prescription.disease.replace(/\s+/g, '_')}_${prescription.date.replace(/\//g, '-')}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up the URL
  URL.revokeObjectURL(url);
  
  // Note: For actual PDF generation, you would typically use a library like jsPDF
  // This creates an HTML file that can be printed to PDF by the user
  console.log('Prescription downloaded as HTML file. Use your browser\'s print function to save as PDF.');
}
