
export interface Prescription {
  disease: string;
  medicines: Array<{
    name: string;
    dosage: string;
    notes?: string;
  }>;
  symptoms: string[];
  date: string;
  doctorName: string;
}

export function formatPrescription(prescription: Prescription): string {
  const { disease, medicines, symptoms, date, doctorName } = prescription;
  
  let formatted = `🏥 MEDICAL PRESCRIPTION\n`;
  formatted += `━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  formatted += `👨‍⚕️ Doctor: ${doctorName}\n`;
  formatted += `📅 Date: ${date}\n\n`;
  
  formatted += `🔍 DIAGNOSIS:\n`;
  formatted += `${disease}\n\n`;
  
  formatted += `🩺 SYMPTOMS:\n`;
  symptoms.forEach((symptom, index) => {
    formatted += `• ${symptom}\n`;
  });
  formatted += `\n`;
  
  formatted += `💊 PRESCRIBED MEDICINES:\n`;
  formatted += `━━━━━━━━━━━━━━━━━━━━━━━\n`;
  
  medicines.forEach((medicine, index) => {
    formatted += `${index + 1}. ${medicine.name}\n`;
    formatted += `   Dosage: ${medicine.dosage}\n`;
    if (medicine.notes) {
      formatted += `   Note: ${medicine.notes}\n`;
    }
    formatted += `\n`;
  });
  
  formatted += `⚠️ IMPORTANT NOTES:\n`;
  formatted += `• Take medicines as prescribed\n`;
  formatted += `• Complete the full course\n`;
  formatted += `• Consult doctor if symptoms persist\n`;
  formatted += `• Keep medicines away from children\n\n`;
  
  formatted += `Generated by MedVoice AI Assistant\n`;
  formatted += `For emergency, call your local emergency number\n`;
  
  return formatted;
}
